#!/usr/bin/env node
// Read the latest Foundry broadcast for a chain and wire the deployed addresses
// into web/.env (NUXT_PUBLIC_*) and watcher/deployment.json — so the frontend and
// watcher both point at the fresh deployment with no hand-copying.
//
//   node scripts/wire-env.mjs [chainId=31337] [network=local] [rpc=http://127.0.0.1:8545]
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ROOT, readDeployment, nuxtEnv } from './deployment.mjs'

const chainId = process.argv[2] || '31337'
const network = process.argv[3] || 'local'
const rpc = process.argv[4] || (network === 'local' ? 'http://127.0.0.1:8545' : '')

const addr = readDeployment(chainId)

// web/.env
const env = nuxtEnv({ network, rpc, addr })
const webEnv = [
  '# Auto-generated by scripts/wire-env.mjs — points the web app at this deployment.',
  ...Object.entries(env).map(([k, v]) => `${k}=${v}`),
  '',
].join('\n')
writeFileSync(join(ROOT, 'web/.env'), webEnv)

// watcher/deployment.json
const watcherDep = {
  rpc: rpc || 'http://127.0.0.1:8545',
  usdc: addr.usdc, registry: addr.registry, policy: addr.policy, router: addr.router, cm: addr.cm,
}
writeFileSync(join(ROOT, 'watcher/deployment.json'), JSON.stringify(watcherDep, null, 2) + '\n')

console.log(`wired ${network} (chain ${chainId}):`)
for (const [k, v] of Object.entries(addr)) console.log(`  ${k.padEnd(11)} ${v}`)
console.log('→ web/.env')
console.log('→ watcher/deployment.json')